package com.example.music.domain;

public class FavourKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favour.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favour.songId
     *
     * @mbggenerated
     */
    private Integer songid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favour.userId
     *
     * @return the value of favour.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favour.userId
     *
     * @param userid the value for favour.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favour.songId
     *
     * @return the value of favour.songId
     *
     * @mbggenerated
     */
    public Integer getSongid() {
        return songid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favour.songId
     *
     * @param songid the value for favour.songId
     *
     * @mbggenerated
     */
    public void setSongid(Integer songid) {
        this.songid = songid;
    }
}