package com.example.music.domain;

public class Type extends TypeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.agreeNum
     *
     * @mbggenerated
     */
    private Integer agreenum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.agreeNum
     *
     * @return the value of type.agreeNum
     *
     * @mbggenerated
     */
    public Integer getAgreenum() {
        return agreenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.agreeNum
     *
     * @param agreenum the value for type.agreeNum
     *
     * @mbggenerated
     */
    public void setAgreenum(Integer agreenum) {
        this.agreenum = agreenum;
    }
}