package com.example.music.domain;

public class TypeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.songId
     *
     * @mbggenerated
     */
    private Integer songid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.tagId
     *
     * @mbggenerated
     */
    private Integer tagid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.songId
     *
     * @return the value of type.songId
     *
     * @mbggenerated
     */
    public Integer getSongid() {
        return songid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.songId
     *
     * @param songid the value for type.songId
     *
     * @mbggenerated
     */
    public void setSongid(Integer songid) {
        this.songid = songid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.tagId
     *
     * @return the value of type.tagId
     *
     * @mbggenerated
     */
    public Integer getTagid() {
        return tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.tagId
     *
     * @param tagid the value for type.tagId
     *
     * @mbggenerated
     */
    public void setTagid(Integer tagid) {
        this.tagid = tagid;
    }
}