package com.example.music.dao;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import com.example.music.domain.FavourKey;

@Mapper
public interface FavourMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(FavourKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbggenerated
     */
    int insert(FavourKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbggenerated
     */
    int insertSelective(FavourKey record);

    int addFavour(FavourKey favour);
    int deleteFavour(Integer userid, Integer songid);
    int searchFavour(Integer userid, Integer songid);
    List<FavourKey> allFavourofUser(Integer userid);
}