package com.example.music.dao;
import org.apache.ibatis.annotations.Mapper;

import com.example.music.domain.Song;

import java.util.List;

@Mapper
public interface SongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbggenerated
     */
    int insert(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbggenerated
     */
    int insertSelective(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbggenerated
     */
    Song selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Song record);

    int addSong(Song song);
    int updateSong(Song song);
    int deleteSong(Integer songid);

    List<Song> searchSong(String keyword);;
    List<Song> songOfId(Integer songid);
    List<Song> allSong();
}