package com.example.music.dao;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import com.example.music.domain.Type;
import com.example.music.domain.TypeKey;
@Mapper
public interface TypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbggenerated
     */
    int insert(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbggenerated
     */
    int insertSelective(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbggenerated
     */
    Type selectByPrimaryKey(TypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Type record);

    int addType(Type type);
    int deleteType(Integer songid, Integer tagid);
    int updateType(Integer songid, Integer tagid);
    List<Type> allType();
    List<Type> allTypeofSong(Integer songid);
    List<Type> allSongofTag(Integer tagid);
}